#!/bin/bash
echo -n "s for SecureRM | n for simple: "
read choice
case $choice in
	"s") echo "srm-ing firefox profile"
	srm -rf .mozilla/firefox/pr5i5uyq.default/*.sqlite
	srm -rf .mozilla/firefox/pr5i5uyq.default/Cache/  
	srm -rf .mozilla/firefox/pr5i5uyq.default/OfflineCache/
	srm -rf .mozilla/firefox/pr5i5uyq.default/bookmarkbackups/
	srm -rf .mozilla/firefox/Crash\ Reports/
	echo "srm-ing home"
	srm -rf .adobe
	srm -rf .macromedia
	echo "done" ;;
	
	"n") echo "rm-ing firefox profile"
	rm -rf .mozilla/firefox/pr5i5uyq.default/*.sqlite
	rm -rf .mozilla/firefox/pr5i5uyq.default/Cache/  
	rm -rf .mozilla/firefox/pr5i5uyq.default/OfflineCache/
	rm -rf .mozilla/firefox/pr5i5uyq.default/bookmarkbackups/
	rm -rf .mozilla/firefox/Crash\ Reports/
	echo "rm-ing home"
	rm -rf .adobe
	rm -rf .macromedia
	echo "done" ;;

	*) echo "no choice?" ;;

esac
